site_name: GME Package Documentation
pages:
   - Introduction: index.md
   - Getting started: getting_started.md
   - Tutorials:
       - Estimation: estimation_tutorial.md
   - Methodology: estimate_technical.md
   - API Reference:
       - Data Construction:
           - EstimationData: api_docs/EstimationData.md
       - Model Estimation:
           - EstimationModel: api_docs/EstimationModel.md
           - estimate: api_docs/estimate_method.md
           - format_regression_table: api_docs/format_regression_table.md
           - combine_sector_results: api_docs/combine_sector_results.md
           - load_estimation: api_docs/load_estimation.md
           - save_estimation: api_docs/save_estimation.md
           - SlimResults: api_docs/SlimResults.md

   - About: about.md

theme:
  name: 'material'

markdown_extensions:
  - footnotes
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.arithmatex
